name: 'Tinify Action'
description: 'Compress and resize images with the Tinify API'
author: 'namoscato'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  api_key:
    description: 'Tinify API key'
    required: true
  github_token:
    description: 'GITHUB_TOKEN secret'
    required: true
